// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// LoginPost implements POST /login operation.
//
// Authentication.
//
// POST /login
func (UnimplementedHandler) LoginPost(ctx context.Context, req OptLogin) (r *Token, _ error) {
	return r, ht.ErrNotImplemented
}
